FROM node:12-alpine

RUN apk add bash sudo curl
SHELL ["/bin/bash", "-c"]
RUN node --version

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . ./
RUN ./build
RUN ls -l /app/dist/google-auth-library-token-alpine
RUN ldd /app/dist/google-auth-library-token-alpine
RUN ( /app/dist/google-auth-library-token-alpine || true ) 2>&1 | grep -F 'GOOGLE_APPLICATION_CREDENTIALS environment variable is not set!'

ENTRYPOINT [ "/app/dist/google-auth-library-token" ]
