#!/bin/bash
set -euo pipefail

test -d node_modules || npm install
./build

export GOOGLE_APPLICATION_CREDENTIALS="$(realpath GOOGLE_APPLICATION_CREDENTIALS.example)"
test -f "$GOOGLE_APPLICATION_CREDENTIALS" || { echo "GOOGLE_APPLICATION_CREDENTIALS file '$GOOGLE_APPLICATION_CREDENTIALS' does not exist" ; exit 1 ; }
dist/google-auth-library-token
